services:
  postgres:
    image: postgres:16.10
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack endpoint
    environment:
      - SERVICES=s3 # Specify the AWS services you need
      - DEFAULT_REGION=ap-southeast-7 # Set a default region
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "./init-scripts:/etc/localstack/init/ready.d"
volumes:
  postgres-data: