logging:
  level:
    io:
      awspring:
        cloud: debug
spring:
  mvc:
    view:
      prefix: '/templates/'
  application:
    name: demo
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydatabase}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  cloud:
    config:
      import-check:
        enabled: false
    aws:
      s3:
        bucket: ${SPRING_CLOUD_AWS_S3_BUCKET:demo-bucket}
        enabled: true
        region: ${SPRING_CLOUD_AWS_S3_REGION:ap-southeast-7}
      credentials:
        access-key: test
        secret-key: test
      endpoint: ${SPRING_CLOUD_AWS_ENDPOINT:http://localhost:4566}
  threads:
    virtual:
      enabled: true
  modulith:
    # modulith settings
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enable: true
  show-actuator: true

lazada:
  product:
    url : ${LAZADA_PRODUCT_URL:https://api.lazada.co.th/rest}
    appKey: ${LAZADA_APP_KEY:}
    appSecret: ${LAZADA_APP_SECRET:}
shopee:
  product:
      url: ${SHOPEE_PRODUCT_URL:https://partner.shopeemobile.com/api/v2/product}
  accessToken: ${SHOPEE_ACCESS_TOKEN:}
  partnerId: ${SHOPEE_PARTNER_ID:}
tiktok:
  product:
    url: ${TIKTOK_PRODUCT_URL:https://open-api.tiktok.com/product/v1}
  accessToken: ${TIKTOK_ACCESS_TOKEN:}
  appKey: ${TIKTOK_APP_KEY:}
  appSecret: ${TIKTOK_APP_SECRET:}
  shopCipher: ${TIKTOK_SHOP_CIPHER:}
  openApiUrl: ${TIKTOK_OPEN_API_URL:https://open-api.tiktokglobalshop.com}
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true