logging:
  level:
    io:
      awspring:
        cloud: debug
spring:
  mvc:
    view:
      prefix: '/templates/'
  application:
    name: demo
  cloud:
    config:
      import-check:
        enabled: false
    aws:
      s3:
        bucket: ${SPRING_CLOUD_AWS_S3_BUCKET:demo-bucket}
        enabled: true
        region: ${SPRING_CLOUD_AWS_S3_REGION:ap-southeast-7}
      credentials:
        access-key: test
        secret-key: test
      endpoint: ${SPRING_CLOUD_AWS_ENDPOINT:http://localhost:4566}
  threads:
    virtual:
      enabled: true
  modulith:
    events:
      mongodb:
        transaction-management:
          enabled: false
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enable: true
  show-actuator: true
integration:
  tiktok:
    appKey: ${INTEGRATION_TIKTOK_APP_KEY:}
    appSecret: ${INTEGRATION_TIKTOK_APP_SECRET:}
    accessToken: ${INTEGRATION_TIKTOK_ACCESS_TOKEN:}
    openApiUrl: ${INTEGRATION_TIKTOK_OPEN_API_URL:https://open-api.tikTokglobalshop.com}
    shopCipher: ${INTEGRATION_TIKTOK_SHOP_CIPHER:}
lazada:
  product:
    url : ${LAZADA_PRODUCT_URL:https://api.lazada.co.th/rest}
shopee:
  product:
      url: ${SHOPEE_PRODUCT_URL:https://partner.shopeemobile.com/api/v2/product}
  accessToken: ${SHOPEE_ACCESS_TOKEN:}
  partnerId: ${SHOPEE_PARTNER_ID:}
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true