spring:
  mvc:
    view:
      prefix: '/templates/'
  application:
    name: demo
  cloud:
    config:
      import-check:
        enabled: false
  threads:
    virtual:
      enabled: true

integration:
  tiktok:
    appKey: ${INTEGRATION_TIKTOK_APP_KEY:}
    appSecret: ${INTEGRATION_TIKTOK_APP_SECRET:}
    accessToken: ${INTEGRATION_TIKTOK_ACCESS_TOKEN:}
    openApiUrl: ${INTEGRATION_TIKTOK_OPEN_API_URL:https://open-api.tikTokglobalshop.com}
    shopCipher: ${INTEGRATION_TIKTOK_SHOP_CIPHER:}
