logging:
  level:
    io:
      awspring:
        cloud: debug
spring:
  application:
    name: demo
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydatabase}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    liquibase-schema: public
  cloud:
    config:
      import-check:
        enabled: false
    aws:
      s3:
        bucket: ${SPRING_CLOUD_AWS_S3_BUCKET:demo-bucket}
        enabled: true
        region: ${SPRING_CLOUD_AWS_S3_REGION:ap-southeast-7}
      credentials:
        access-key: test
        secret-key: test
      endpoint: ${SPRING_CLOUD_AWS_ENDPOINT:http://localhost:4566}
  threads:
    virtual:
      enabled: true
  modulith:
    # modulith settings
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enable: true
  show-actuator: true

platform:
  oauth:
    callback-url: ${PLATFORM_OAUTH_CALLBACK_URL:https://589ad4c65c91.ngrok-free.app/platform/callback}

  lazada:
    product:
      url : ${LAZADA_PRODUCT_URL:https://api.lazada.co.th/rest}
    oauth:
      auth-url: ${LAZADA_AUTH_URL:https://auth.lazada.com/oauth/authorize}
      token-url: ${LAZADA_TOKEN_URL:https://auth.lazada.com/rest/auth/token/create}
      refresh-url: ${LAZADA_REFRESH_URL:https://auth.lazada.com/rest/auth/token/refresh}
    app:
      key: ${LAZADA_APP_KEY:}
      secret: ${LAZADA_APP_SECRET:}

  shopee:
    product:
      url: ${SHOPEE_PRODUCT_URL:https://partner.shopeemobile.com/api/v2/product}
    oauth:
      auth-url: ${SHOPEE_AUTH_URL:https://partner.shopeemobile.com/api/v2/shop/auth_partner}
      token-url: ${SHOPEE_TOKEN_URL:https://partner.shopeemobile.com/api/v2/auth/token/get}
      refresh-url: ${SHOPEE_REFRESH_URL:https://partner.shopeemobile.com/api/v2/auth/access_token/get}
    app:
      partner-id: ${SHOPEE_PARTNER_ID:}
      secret: ${SHOPEE_APP_SECRET:}
    access-token: ${SHOPEE_ACCESS_TOKEN:}

  tiktok:
    product:
      url: ${TIKTOK_PRODUCT_URL:https://open-api.tiktok.com/product/v1}
    oauth:
      auth-url: ${TIKTOK_AUTH_URL:https://services.tiktokshop.com/open/authorize}
      token-url: ${TIKTOK_TOKEN_URL:https://auth.tiktok-shops.com/api/v2/token/get}
      refresh-url: ${TIKTOK_REFRESH_URL:https://auth.tiktok-shops.com/api/v2/token/refresh}
    app:
      key: ${TIKTOK_APP_KEY:}
      secret: ${TIKTOK_APP_SECRET:}
    shop-cipher: ${TIKTOK_SHOP_CIPHER:}
    open-api-url: ${TIKTOK_OPEN_API_URL:https://open-api.tiktokglobalshop.com}
    access-token: ${TIKTOK_ACCESS_TOKEN:}

# Vodbot Configuration
vodbot:
  s3:
    bucket: ${VODBOT_S3_BUCKET:vodbot-videos}
    region: ${VODBOT_S3_REGION:us-east-1}
    video-prefix: ${VODBOT_S3_VIDEO_PREFIX:videos/}
  recording:
    max-session-duration: ${VODBOT_MAX_SESSION_DURATION:PT4H}
    max-video-size: ${VODBOT_MAX_VIDEO_SIZE:5368709120}
    supported-formats:
      - video/mp4
      - video/webm
      - video/quicktime
      - video/x-msvideo
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true