spring:
  mvc:
    view:
      prefix: '/templates/'
  application:
    name: demo
  cloud:
    config:
      import-check:
        enabled: false
  threads:
    virtual:
      enabled: true
  modulith:
    events:
      mongodb:
        transaction-management:
          enabled: false
integration:
  tiktok:
    app-key: ${INTEGRATION_TIKTOK_APP_KEY:}
    app-secret: ${INTEGRATION_TIKTOK_APP_SECRET:}
    access-token: ${INTEGRATION_TIKTOK_ACCESS_TOKEN:}
    open-api-url: ${INTEGRATION_TIKTOK_OPEN_API_URL:https://open-api.tikTokglobalshop.com}
    shop-cipher: ${INTEGRATION_TIKTOK_SHOP_CIPHER:}
