package com.example.demo.platform.domain;

import lombok.Getter;
import lombok.Setter;
import lombok.Builder;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.UUID;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class BarcodeGenerationLog {
    private UUID id;
    private UUID productId;
    private String barcode;
    private Product.BarcodeType barcodeType;
    private GenerationMethod generationMethod;
    private UUID generatedBy; // User ID who generated (null for auto)
    private Instant createdAt;

    public enum GenerationMethod {
        AUTO_GENERATED,
        MANUAL,
        PLATFORM_PROVIDED
    }

    public boolean isAutoGenerated() {
        return generationMethod == GenerationMethod.AUTO_GENERATED;
    }

    public boolean isManuallyGenerated() {
        return generationMethod == GenerationMethod.MANUAL;
    }
}